/* eslint-disable @typescript-eslint/no-misused-promises */
/* eslint-disable react/no-unescaped-entities */
import { type NextPage } from "next";
import Head from "next/head";
import { Header } from "~/components/header/Header";
import { getUserMetadata } from "~/lib/MetaData";
import { toast } from "react-toastify";
import { AbdullahButton } from "~/components/used/AbdullahButton";

const Page: NextPage = () => {

  const handleCopy = async  () => {
     await navigator.clipboard.writeText(getUserMetadata())
     .then(() => {
      toast("copied successfully  ",{
        className:" !text-white !bg-blue-500",
        hideProgressBar: true,
       })
     })
     .catch(() => {
      toast("failed to delete ",{
        className:" !text-white !bg-blue-500",
        hideProgressBar: true,
       })
     })

  }


  return (
    <>
      <Head>
      <title>ProjectFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main className=" custopn-page-height  justify-center items-center flex w-full bg-gray-50 ">
      <div className='md:w-[70%]  w-full xl:w-[900px] min-h-[500px] flex flex-col  h-fit bg-white rounded-lg shadow-lg'>
      <div className='w-full h-[50px] flex-col flex my-4 justify-center items-start p-4 '>
        <h1 className='text-gray-400 text-md'>add a new team member</h1>
        <p className='text-gray-700 text-lg'>copy your token code and send it to who you want him to join your team </p>
      </div>
      <div className="w-[90%] mx-auto h-[40px] flex gap-x-4  ">
      <input
      value={getUserMetadata()}
      className=" w-full border border-gray-300 px-3 py-1.5 text-base text-gray-700  bg-white bg-clip-padding font-normal rounded-lg shadow-sm  transition  ease-in-out focus:outline-none focus:border-gray-500 focus:ring-1 focus:ring-gray-500"  />       
        <AbdullahButton 
        onClick={handleCopy}
       className="!inline-flex !text-white !font-bold    !justify-center !rounded-md !border !border-gray-300 !bg-gradient-to-r !from-sky-500 !to-indigo-600 !px-4 !py-2 !text-sm   !shadow-sm !hover:bg-gray-50 !focus:outline-none !focus:ring-2 !focus:ring-indigo-500 focus:ring-offset-2 !focus:ring-offset-gray-100">
          copy 
       </AbdullahButton>
      </div>
     
      <div className='w-full h-fit flex gap-x-2 p-4 my-2 flex-col'>
        <div>
        <h1 className='text-gray-400 text-md'>message</h1>
        <p className='text-gray-700 text-lg'>Add a strong message or use out template </p>
        </div>
    <textarea   placeholder='this is your   description about the project'   className={` w-full border border-gray-300 px-3 py-1.5  text-gray-700  bg-white bg-clip-padding  rounded-lg shadow-sm  transition  ease-in-out focus:outline-none focus:border-gray-500 focus:ring-1 focus:ring-gray-500 mt-1 h-[120px] font-bold text-lg `}/> 
  
      </div>
      <div className='w-full min-h-[100px] h-fit flex flex-col p-4'>
       <div className='h-full w-[90%] flex flex-col '>
          <div>
        <h1 className='text-gray-400 text-md'>memmber's email</h1>
        <p className='text-gray-700 text-lg'>the message ubove will be send to this email </p>
        </div>
        <input  className=" w-full border border-gray-300 px-3 py-1.5 text-base text-gray-700  bg-white bg-clip-padding font-normal rounded-lg shadow-sm  transition  ease-in-out focus:outline-none focus:border-gray-500 focus:ring-1 focus:ring-gray-500"  />       
        </div>
    <div className='w-full h-[100px] gap-x-4 bg-white flex items-center justify-end px-6'>
    <AbdullahButton 
          className="!inline-flex   !font-bold   !justify-center !rounded-md border !border-gray-300 !bg-white !px-4 py-2 !text-sm  !text-gray-700 !shadow-sm !hover:bg-gray-50 !focus:outline-none !focus:ring-2 !focus:ring-indigo-500 !focus:ring-offset-2 !focus:ring-offset-gray-100">
           cancel
        </AbdullahButton>
        <AbdullahButton 
        className="!inline-flex !text-white !font-bold    !justify-center !rounded-md !border !border-gray-300 !bg-gradient-to-r !from-sky-500 !to-indigo-600 !px-4 !py-2 !text-sm   !shadow-sm !hover:bg-gray-50 !focus:outline-none !focus:ring-2 !focus:ring-indigo-500 focus:ring-offset-2 !focus:ring-offset-gray-100">
           invite 
        </AbdullahButton>
        
    </div>
    </div>
    </div>
      </main>
    </>
  );
};

export default Page;