import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "~/components/header/Header";
import { getProjectMetaData, getUserMetadata, deteProjectMetaData } from "~/lib/MetaData";
import { AbdullahButton } from "~/components/used/AbdullahButton";

import { api } from "~/utils/api";
import toast from "react-hot-toast";
import { CookieSettings } from "~/components/common/cookies-settings";

const Page: NextPage = () => {
  const projectMutation = api.projectRouter.delete_project.useMutation({
    onSuccess() {
      deteProjectMetaData();
      toast.success("Your project has been deleted successfully");
    },
    onError() {
      toast.error("Something went wrong");
    },
  });

  const deleteMyProject = () => {
    projectMutation.mutate({
      project_id: getProjectMetaData(),
    });
  };

  return (
    <>
      <Head>
        <title>ProjectFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main className="custopn-page-height   w-full bg-gray-50 py-8">
        <div className="w-full max-w-6xl min-h-[500px] mx-auto  flex p-4 pt-12 mt-8 flex-col  h-fit bg-white rounded-lg shadow-lg">


        {/* <CookieSettings /> */}

          <div className="w-[95%] my-4 p-4 mx-auto min-h-[200px]  rounded-lg border flex flex-col">
         
            <div className="w-full h-[140px] flex flex-col justify-start">
              <h4 className="text-xl font-semibold text-gray-900 font-sans text-start">Supprimer mon projet</h4>
              <p className="text-md font-sans text-gray-400 text-start">
              En sélectionnant cette option, vous êtes sur le point de démarrer la suppression de votre projet de la plateforme de gestion de projets. Il est essentiel de comprendre que cette action est irréversible, ce qui signifie qu'une fois terminée, elle ne pourra pas être annulée. Par conséquent, nous vous recommandons vivement de faire preuve de prudence et de vous assurer que c'est bien le choix que vous souhaitez faire.
              </p>
            </div>
            <div className="h-[60px] w-full flex justify-end items-center p-4">
              <AbdullahButton onClick={deleteMyProject} isLoading={projectMutation.isLoading} className="bg-red-500 text-white font-semibold">
              Supprimer mon projet
              </AbdullahButton>
            </div>
          </div>

          <div className="w-[95%] my-4 p-4 mx-auto h-[200px] rounded-lg border flex flex-col">
            <div className="w-full h-[140px] flex flex-col justify-start">
              <h4 className="text-xl font-semibold text-gray-900 font-sans text-start">Supprimer mon compte personnel</h4>
              <p className="text-md font-sans text-gray-400 text-start">
              ProjectFlow accorde une grande importance à la confidentialité et au contrôle des données de nos utilisateurs. Nous offrons cette option pour vous donner un contrôle total sur votre compte et son contenu. En supprimant votre compte personnel, toutes les informations, fichiers et autres données associées à votre compte seront définitivement supprimés de nos serveurs. Cela inclut tous les projets, documents, paramètres et préférences utilisateur que vous avez personnalisés pendant votre utilisation de la plateforme
              </p>
            </div>
            <div className="h-[60px] w-full flex justify-end items-center p-4">
              <AbdullahButton className="bg-red-500 text-white font-semibold">
              Supprimer mon compte
              </AbdullahButton>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Page;