import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Header } from "~/components/header/Header";
import { Form } from "~/components/used/Form";
import { FormContainer } from "~/components/used/FormContainer";
import { RowGridText } from "~/components/typography/RowGridText";
import { TextField } from "~/components/used/TextField";
import { ExecutingSidebar } from "~/components/sideBars/ExecutingSidebar";



const Page: NextPage = () => {
  const [isOpen , setIsOpen] = useState<boolean>(true)
  return (
    <>
      <Head>
      <title>ProjectFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main className=" custopn-page-height  flex w-full bg-gray-50 ">
      <ExecutingSidebar isOpen={isOpen} setIsOpen={setIsOpen} />
       <FormContainer className ={` ${isOpen ? "ml-[20rem]" : "ml-[5rem]"}`}>
 
      <Form  >
      <div className="bg-white px-4 py-5 sm:p-6">
      <div className="grid grid-cols-6 lg:grid-cols-12 gap-6">
                  
            <RowGridText text="CONTRACTOR STATUS REPORT" />
            <RowGridText text="La clôture de projet est la phase finale où toutes les activités, les livrables et les objectifs sont terminés, et le projet est officiellement clôturé, visant à valider le succès du projet et faciliter la transition vers les opérations en cours ou les projets ultérieurs" small />
            
               <TextField
                isLoading={false}
                lable="Scope Performance This Reporting Period"
                value={""}
                onChange={(e) => console.log(e) }
               />
                <TextField
                isLoading={false}
                lable="Quality Performance This Reporting Period"
                value={""}
                onChange={(e) => console.log(e) }
               />
                <TextField
                isLoading={false}
                lable="Schedule Performance This Reporting Period"
                value={""}
                onChange={(e) => console.log(e) }
               />
                <TextField
                isLoading={false}
                lable="Planned Corrective or Preventive Action"
                value={""}
                onChange={(e) => console.log(e) }
               />
                <TextField
                isLoading={false}
                lable="Cost Performance This Reporting Period"
                value={""}
                onChange={(e) => console.log(e) }
               />
                <TextField
                isLoading={false}
                lable="Forecast Performance for Future Reporting Periods"
                value={""}
                onChange={(e) => console.log(e) }
               />
                <TextField
                isLoading={false}
                lable="Claims or Disputes "
                value={""}
                onChange={(e) => console.log(e) }
               />

              <TextField
                isLoading={false}
                lable="Risks"
                value={""}
                onChange={(e) => console.log(e) }
               />
                <TextField
                isLoading={false}
                lable="Issues "
                value={""}
                onChange={(e) => console.log(e) }
               />
              <TextField
                isLoading={false}
                lable="Comments "
                value={""}
                onChange={(e) => console.log(e) }
               />

        </div>
      </div>
   
       </Form>
  </FormContainer>
      </main>
    </>
  );
};

export default Page;