import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { GanttTask } from "~/components/common/GanttTask";
import { Header } from "~/components/header/Header";
import { ExecutingSidebar } from "~/components/sideBars/ExecutingSidebar";
import { AbdullahTable, ItemTable } from "~/components/used/AbdullahTable";
import { Form } from "~/components/used/Form";
import { FormContainer } from "~/components/used/FormContainer";




const Page: NextPage = () => {
  const [isOpen , setIsOpen] = useState<boolean>(true)

  return (
    <>
      <Head>
      <title>ProjectFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main className=" custopn-page-height  flex w-full bg-gray-50 ">
       <ExecutingSidebar isOpen={isOpen} setIsOpen={setIsOpen} />
       <FormContainer className ={` ${isOpen ? "ml-[20rem]" : "ml-[0]"}`}>
    
      <Form >
      <div className="bg-white px-4 py-5 sm:p-6">
      <div className="grid grid-cols-6 lg:grid-cols-12 gap-6">
          <div className="col-span-12 ">
            <GanttTask />
           </div>
          </div>  
     </div>
       </Form>
  </FormContainer>
      </main>
    </>
  );
};

export default Page;