import { type NextPage } from "next";
import Head from "next/head";
import { Header } from "~/components/header/Header";
import DocsSideBar from "~/components/docsComponents/DocsSideBar";
import { GeneraleBuilder } from "~/components/docsComponents/generale-builder";


const Page: NextPage = () => {
  
 
  return (
    <>
      <Head>
      <title>ProjectFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main className=" custopn-page-height flex w-full justify-center items-center container bg-white ">
        <DocsSideBar  />
       <div
        className="ml-[20rem] w-[80%] grid grid-cols-1 lg:grid-cols-2 gap-4 h-full pt-8 pb-8 "
       >
           <GeneraleBuilder 
              title="Matrice d'analyse des parties prenantes"
              color=""
              description="Un outil pour identifier et évaluer l'impact des parties prenantes sur le projet."
              phase="Inisiating"
            />
             <GeneraleBuilder 
              title="Plan de gestion des parties prenantes"
              color=""
              description=" Un document détaillant les stratégies pour engager, communiquer et gérer les parties prenantes tout au long du projet"
              phase="Inisiating"
            />
             <GeneraleBuilder 
              title="Registre des parties prenantes"
              color=""
              description="Un document répertoriant toutes les parties prenantes identifiées pour le projet, avec leurs informations clés"
              phase="Inisiating"
            />
            <GeneraleBuilder 
              title=" Répertoire de l'équipe"
              color=""
              description="Une liste contenant les coordonnées et les rôles de chaque membre de l'équipe"
              phase="Inisiating"
            />
             <GeneraleBuilder 
              title="Accord de fonctionnement de l'équipe"
              color=""
              description="Un accord décrivant les règles, les normes et les responsabilités au sein de l'équipe de projet"
              phase="Inisiating"
            />
              <GeneraleBuilder 
              title="Rôles et personnalités"
              color=""
              description="Un document décrivant les responsabilités et les caractéristiques personnelles de chaque membre de l'équipe"
              phase="Inisiating"
            />
              <GeneraleBuilder 
              title="Évaluation des performances des membres de l'équipe"
              color=""
              description=" Un processus pour évaluer la performance individuelle des membres de l'équipe de projet"
              phase="Inisiating"
            />
             <GeneraleBuilder 
              title="Rapport d'état des membres de l'équipe"
              color=""
              description=" Un rapport qui fournit des mises à jour sur l'avancement et les activités des membres de l'équipe de proje"
              phase="Inisiating"
            />
       </div>
      </main>
    </>
  );
};

export default Page;