import { type NextPage } from "next";
import Head from "next/head";
import { Header } from "~/components/header/Header";
import DocsSideBar from "~/components/docsComponents/DocsSideBar";
import { GeneraleBuilder } from "~/components/docsComponents/generale-builder";
import { ActivityListBuilder } from "~/components/docsComponents/builders/Activity-list";


const Page: NextPage = () => {
  
 
  return (
    <>
      <Head>
      <title>ProjectFlow</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main className=" custopn-page-height flex w-full justify-center items-center container bg-white ">
        <DocsSideBar  />
       <div
        className="ml-[20rem] w-[80%] grid grid-cols-1 lg:grid-cols-2 gap-4 h-full pt-8 pb-8 "
       >
          <ActivityListBuilder />
             <GeneraleBuilder 
              title="Liste des jalons"
              color=""
              description="Une liste des jalons clés du projet, marquant des points d'achèvement ou d'étape importante"
              phase="Inisiating"
            />
             <GeneraleBuilder 
              title="Planning du projet"
              color=""
              description="Un calendrier détaillé indiquant les dates de début et de fin prévues pour les activités du projet"
              phase="Inisiating"
            />
            <GeneraleBuilder 
              title="Attributs d'activité"
              color=""
              description=" Des informations supplémentaires et spécifiques pour chaque activité du projet, telles que les ressources, les contraintes, les dépendances, etc."
              phase="Inisiating"
            />
             <GeneraleBuilder 
              title="Diagramme de réseau"
              color=""
              description="Une représentation graphique du réseau logique des activités du projet et de leurs interdépendances."
              phase="Inisiating"
            />
              <GeneraleBuilder 
              title="Estimations de durée d'activité"
              color=""
              description="Les estimations du temps nécessaire pour compléter chaque activité du projet."
              phase="Inisiating"
            />
              <GeneraleBuilder 
              title="Feuille de travail d'estimation de la durée"
              color=""
              description="Un document qui contient les détails et les calculs des estimations de durée pour les activités du projet"
              phase="Inisiating"
            />
             <GeneraleBuilder 
              title="Plan de gestion du planning"
              color=""
              description="Un document détaillant comment le calendrier du projet sera développé, mis à jour et contrôlé tout au long du projet."
              phase="Inisiating"
            />
       </div>
      </main>
    </>
  );
};

export default Page;